services:
  model:
    container_name: model
    image: pytorch/torchserve:latest
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    # volumes:
    #   - ./models/build:/home/model-server/model-store
    build:
      args:
        gpus: all
