name: StyleMixer

volumes:
  static:
  database:

services:
  backend:
    container_name: backend
    build: ../backend
    ports:
      - 8000:8000
    volumes:
      - database:/backend/storage

  frontend:
    container_name: frontend
    build: ../frontend
    volumes:
      - static:/frontend/build

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ../infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/frontend_static/
      - database/images:/media/

  # model:
  #   container_name: model
  #   image: pytorch/torchserve:latest
  #   restart: always
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #     - 8082:8082
  #   # volumes:
  #   #   - ./models/build:/home/model-server/model-store
  #   build:
  #     args:
  #       gpus: all
