name: StyleMixer

volumes:
  static:
  database:

services:
  backend:
    container_name: backend
    build: ../backend
    ports:
      - 8000:8000
    volumes:
      - database:/backend/storage
    env_file: ../.env

  model:
    container_name: model
    build: ../model
    ports:
      - 8080:8080
    volumes:
      - ../model/data:/model/data
      - ../model/data/nets:/root/.cache/torch/hub/checkpoints/
    env_file: ../.env

  frontend:
    container_name: frontend
    build: ../frontend
    volumes:
      - static:/frontend/build
    env_file: ../.env

  nginx:
    container_name: proxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "81:80"
    depends_on:
      - backend
      - frontend
      - model
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/frontend_static/
      - database:/media/
