name: Main workflow

on:
  push:
    branches:
      - main
jobs:

  test_backend:
    - name: Check out source repository
      uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.1"
      run: cd ./backend
      run: pip install flake8
    - name: flake8 Lint
      run: flake8

  test_frontend:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '21.6.0'
      run: cd ./frontend
      run: npm ci
    - name: Lint TS and CSS
      run: npm run lint:ts
      run: npm run lint:css

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - test_backend
      - test_frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      # - name: Executing remote ssh commands to deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd StyleMixer/
      #       git checkout main
      #       git pull
      #       docker compose -f docker-compose.yml down
      #       docker compose -f docker-compose.yml build
      #       docker compose -f docker-compose.yml up -d
      #       docker exec assistent alembic upgrade head
      # - name: Replacing the NGINX proxy configuration file
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd StyleMixer/config
      #       rm /etc/nginx/sites-enabled/default
      #       cp nginx.conf /etc/nginx/sites-enabled/default
      #       systemctl reload nginx

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_LIC }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
