name: Main workflow

on:
  push:
    branches:
      - main
jobs:
  test_backend:
      runs-on: ubuntu-latest
      steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Install depends
        run: |
          cd ./backend
          pip install flake8
      - name: Lint PEP8
        run: |
          cd ./backend
          flake8

  test_frontend:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '21.6.0'
      - name: Instal depends
        run: |
          cd ./frontend
          npm ci
      - name: Lint TS and CSS
        run: |
          cd ./frontend
          npm run lint:ts
          npm run lint:css

  test_model:
      runs-on: ubuntu-latest
      steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
      - name: Install depends
        run: |
          cd ./model
          pip install flake8
      - name: Lint PEP8
        run: |
          cd ./model
          flake8

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - test_backend
      - test_frontend
      - test_model
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          # password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd StyleMixer/
            sudo git checkout main
            sudo git pull
            cd infra/
            sudo docker compose -f docker-compose.yml down
            sudo docker compose -f docker-compose.yml build
            sudo docker compose -f docker-compose.yml up -d
            sudo docker exec backend alembic upgrade head

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_LIC }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: StyleMixer - коммит выполнен!
